### ISSUE TITLE
Incompatible dependencies in elm.json

### ISSUE THREAD

**Issue by NiavlysB** [MartinSStewart/meetdown#10]
I just tried cloning the repo and running `lamdera live`, and it says that the dependencies in elm.json are not compatible.

I use the latest version from the master branch and did not touch anything. `lamdera make` gives the same error.

![image](https://user-images.githubusercontent.com/3757523/124571837-719c1c80-de48-11eb-9106-006a702b7417.png)

**Comment by MartinSStewart** [comment]
Could you try running `lamdera reset` and then attempt `lamdera live` again? I've seen this problem before, I'm not sure what causes it but usually `lamdera reset` is enough to fix it.

**Comment by NiavlysB** [comment]
Yeah I’ve just seen something in Slack about that. I’ll try that, I was just afraid of losing more than just the package cache, but I’ll backup everything just in case.

**Comment by NiavlysB** [comment]
Yep, working perfectly now after a `lamdera reset`! I guess it just has to do with the very first lamdera install on a given machine.
