### ISSUE TITLE
Copy previous event

### ISSUE THREAD

**Issue by supermario** [MartinSStewart/meetdown#15]
When I'm creating a new Event, I often want to quick-start the new one by coping all the old content (title, description, time of day, meetup link, etc) from a previous event, and then edit it.

Right now once an event has passed it's no longer editable, so I can't get my original meeting description markdown which is a little annoying.

It would be really cool if a summary list of past events showed up under a "Copy from past event" title and I could click one to pre-fill the new event form.

**Comment by MartinSStewart** [comment]
I've added a "copy previous event" button now that will fill in any empty fields (excluding the date field) when you are creating a new event. It doesn't let you pick arbitrary events but it's probably good enough for now.
