### ISSUE TITLE
"Copy previous event" copied first event

### ISSUE THREAD

**Issue by supermario** [MartinSStewart/meetdown#16]
- I went to create a new event
- I clicked copy previous event
- It copied the event before the last event (the first event)

Not a particularly big deal in my case, but perhaps it should do what it says on the tin 😀

NB: I'm happy to tackle this one next week unless someone beats me to it!

**Comment by MartinSStewart** [comment]
Oops. I checked to make sure I didn't get the list of events in the wrong order but I guess I got it wrong anyway.
