### ISSUE TITLE
Edit event doesn't show original time of day if it's AM

### ISSUE THREAD

**Issue by MartinSStewart** [MartinSStewart/meetdown#25]
![image](https://user-images.githubusercontent.com/5068391/160610835-66f9e57a-f479-4104-bf88-c383a164cd1f.png)
The time input is empty if the time value is AM instead of PM

**Comment by MatsLanGoH** [comment]
I was able to reproduce and narrow this down on local. 

The bug seems to be caused by having a single-digit hour value, i.e. any time between 00:00 and 09:59 causes the input field to show `--:--`.

Here's the accompanying error message.

```
The specified value "9:47" does not conform to the required format.  The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.
```

**Comment by MatsLanGoH** [comment]
Modifying `Ui.timeToString` to left-pad hours too would fix the input issue - but also causes the event overview to have a leading "0" for single-digit hours.

https://github.com/MartinSStewart/meetdown/blob/3c299c2ea0062bd3caf82c633d9b6925a626ce7b/src/Ui.elm#L640-L644

```Elm
timeToString : Time.Zone -> Time.Posix -> String
timeToString timezone time =
    String.padLeft 2 '0' (String.fromInt (Time.toHour timezone time))
        ++ ":"
        ++ String.padLeft 2 '0' (String.fromInt (Time.toMinute timezone time))
```

![Screenshot 2022-03-31 at 12 17 19](https://user-images.githubusercontent.com/13265785/161033008-16a21e99-ca16-4e0a-a599-6cbf8ef8c8f0.png)
![Screenshot 2022-03-31 at 12 17 43](https://user-images.githubusercontent.com/13265785/161033011-0fbf0f6c-53bd-4073-b182-0390190054d2.png)

**Comment by MatsLanGoH** [comment]
Never mind, I discovered a `Ui.timestamp` function to take care of handling the time input field.

https://github.com/MartinSStewart/meetdown/blob/3c299c2ea0062bd3caf82c633d9b6925a626ce7b/src/Ui.elm#L691-L695

However, this method isn't being used for the `PressedEditEvent` case, which seems to trigger the bug. I'll create a fix in a bit.
https://github.com/MartinSStewart/meetdown/blob/8d036335f4a6db37100c1b6924970b32d0a1480d/src/GroupPage.elm#L568
