### ISSUE TITLE
Online and in person

### ISSUE THREAD

**Issue by CharlonTank** [MartinSStewart/meetdown#30]
Hello!

I showed elm and Lamdera to a student and we did a little PR to your project.
This student created an event on Meetdown and all the events he usually create are online and in person so that's why we did this.
Goal was to add a 3rd possibility to create an event online and in person.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4601603/211099493-87b15af6-0493-43f9-a71c-72fb95b8ad66.png">

Here is the PR: https://github.com/MartinSStewart/meetdown/pull/31

Tell me what you think! :)

**Comment by MartinSStewart** [comment]
It's live now. Thanks for the PR!

**Comment by CharlonTank** [comment]
Wow! So fast! Really happy it's in production!

For the i18n, sure we can have a little talk!
