### ISSUE TITLE
Dark Reader compatibility

### ISSUE THREAD

**Issue by cdevienne** [MartinSStewart/meetdown#32]
When the "Dark Reader" (https://darkreader.org) extension is enabled, the pages appear empty. I had a look at the domtree, it is empty as well.
I have no idea why it does that, usually it plays well with elm apps.
The funny thing is that if we enable the extension after the page initial load, it works as expected but then the navigation is not working, ie when we click a link the url changes but not the page itself.
I tested on both firefox and chromium, same issue.

**Comment by MartinSStewart** [comment]
That's strange. I don't know how darkreader works internally so it would be hard for me to debug this. It seems like the darkreader github repo tracks websites that don't work with their browser extension https://github.com/darkreader/darkreader/issues?q=label%3A%22Broken+Website%22+ . Maybe it would be better to post your issue there?

Also, would an alternative solution be for meetdown to support a dark mode directly or does darkreader do additional stuff?

**Comment by lue-bird** [comment]
Same behavior with the dark reader [firefox extension: "dark background, light text](https://github.com/m-khvoinitsky/dark-background-light-text-extension) on stylesheet processo. Invert is fine, simple css edits work for the individual pages but not for the search results page.

**Comment by cdevienne** [comment]
Providing a dark mode would be great indeed.
I will report the issue to darkreader too.
Still, I find it odd that it has such a behavior, which I never saw on another elm app, so it makes me curious.

**Comment by MartinSStewart** [comment]
Dark theme implemented! You can toggle it with the sun/moon emoji in the top right and the website should also automatically detect if the user has preferred theme set to dark.
![image](https://user-images.githubusercontent.com/5068391/213807581-1a746bd0-e7f3-4913-b903-9f2e91da961c.png)

**Comment by cdevienne** [comment]
I love it thanks!
