### ISSUE TITLE
Translations of dates

### ISSUE THREAD

**Issue by CharlonTank** [MartinSStewart/meetdown#35]
I just saw this:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/4601603/225342718-2b513c04-344b-4b80-9920-64f40feb8b4c.png">

As you can see "January 1st" is a translation from Date from justinmimbs date library. 
here: https://github.com/CharlonTank/meetdown/blob/72e5557df0ba238a0c549e51a3e4f961315bf29e/src/GroupPage.elm#L2659
and here:
https://github.com/CharlonTank/meetdown/blob/72e5557df0ba238a0c549e51a3e4f961315bf29e/src/Ui.elm#L665

As a solution:
We could use https://package.elm-lang.org/packages/justinmimbs/date/latest/Date#formatWithLanguage but this includes 2 consequences:
- We need to create 2 custom `Date.Language`s. (`Date.format` uses `Date.language_en`) so we need to create `language_es` and `language_fr`.
- We have to pass the language when we call `Date.formatWithLanguage` and doing this will break Meetdown's i18n design pattern.

To keep the same design pattern, maybe we could add the dateLanguageFr and dateLanguageEs to the `Texts` record?

**Comment by CharlonTank** [comment]
I'm working on this

**Comment by MartinSStewart** [comment]
Hey sorry for the late reply. Haven't had time to think about which approach works best but if you're working on it I'll let you decide which approach you find works best.

**Comment by CharlonTank** [comment]
> Hey sorry for the late reply. Haven't had time to think about which approach works best but if you're working on it I'll let you decide which approach you find works best.

No problem :)

Here is the PR: https://github.com/MartinSStewart/meetdown/pull/36

**Comment by MartinSStewart** [comment]
Good work, I've merged your PR
