### ISSUE TITLE
Upcoming events show "X people attended"

### ISSUE THREAD

**Issue by edkelly303** [MartinSStewart/meetdown#37]
![Screenshot_2023-04-20-06-46-19-94_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/12986896/233269465-c2557b55-3b88-4e83-a27f-4ea223f20828.jpg)
"X people plan to attend" might be better, if the event is still in the future.

**Comment by MartinSStewart** [comment]
Good catch, should be fixed now
