### ISSUE TITLE
Feature request: add 24h time format.

### ISSUE THREAD

**Issue by francescortiz** [MartinSStewart/meetdown#8]
It would be nice that there was the regional setting of being able to choose 24h time format associated to your profile. AM/PM feels a bit awkward when you are used to 24h time format.

Apparently, most of the world uses 24h format: https://travel.stackexchange.com/questions/34950/which-large-countries-use-12-hour-time-format-am-pm

Thanks!

**Comment by MartinSStewart** [comment]
Hi, could you clarify what you mean by being able to choose 24h format? All the timestamps should be shown in 24 hour time and if you create event, the time selection input should use your system time format?

**Comment by francescortiz** [comment]
Sure, I was referring to the form to create events:

![image](https://user-images.githubusercontent.com/655264/124163247-b0745000-da9f-11eb-9e1e-7c69e4762cc5.png)

Sorry that I didn't point that out.

**Comment by MartinSStewart** [comment]
Interesting, I guess I've misunderstood how the time input works. I had assumed it would use 24h or AM/PM depending one browser settings. I'll look into how to change that.

**Comment by francescortiz** [comment]
Well, I have my browser set to 1st Catalan, then US English, but I moved Spanish to the top and I was still getting AM/PM. I use English over the internet because of the quality of IT content, so setting Spanish first is not an option to me. Also English is an official language in Europe that I use with coworkers from all around Europe, because it is the language we all know, but we still use metric system or non-US date formatting. Maybe it is overkill for the current status of the project, but I think that a good approach would be to differentiate regional settings from language in the profile. Simple problem, complex solution :laughing:

**Comment by MartinSStewart** [comment]
I think the only solution to this then is to replace the time input with something custom. That's not unreasonable, a lot of websites use custom date/time inputs, but I think I'll wait with doing that for now and see if I get any more feedback. If that's okay with you then I'll close the issue for now.

**Comment by francescortiz** [comment]
Sure! 👍
